# Usage: conda env create --file conda_QCB_essentials.yml
# Use this environment file to add packages which are necessary for the
# project. Change the project name if needed.
name: QCB_project
channels: 
    - conda-forge
dependencies:
    - python=3.6.9
    - numpy=1.17.2
    - scipy=1.3.1
    - matplotlib=3.1.1
    - pandas=0.22.0
    - seaborn=0.9.0
    - scikit-learn=0.21.3
    - jupyter=1.0.0
    - mdanalysis=0.20.1
    - pip
